### ISSUE TITLE
depot inexistant

### ISSUE THREAD

**Issue by alfman94** [pjap93/gladys-tplink#1]
Bonjour, 

Lors de l'installation du module depuis le mode avancé sous Gladys v3.7.3.
mp2 log indique : 
 (node:1425) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Command failed: git clone --depth=1 //github.com/pjap93/gladys-tplink ./api/hooks/tplink
le dépôt '//github.com/pjap93/gladys-tplink' n'existe pas

Cordialement,

**Comment by pjap93** [comment]
bonjour,
dans le champ URL il faut renseigner toute l'adresse avec le https, d'après ton message il manque celui-ci devant.

réessaye avec toute l'adresse comme ceci
https://github.com/pjap93/gladys-tplink

dis moi si cela est mieux ou pas,

**Comment by alfman94** [comment]
Bonsoir,
Merci pour cette réponse rapide, ou c'est mieux avec l'adresse complète..
😫.
L'installation est passé, je verrais demain pour le paramétrage.
Merci encore et bonne soirée.

Cordialement

Yoann

**Comment by pjap93** [comment]
super si c'est passé sans problème.

Bonne soirée
